AY2223S1-CS2103-W14-2/tp

docs/_config.yml
docs/index.md

Name of Application need to be changed
Updating the index.md with the new Application name (FoodWhere) so that users can quickly identify the name of the application

Update index.md of documentation with app name

---

docs/team/clarence-chew.md

Add PPP page for Clarence

---

docs/team/hikoya.md

Add PPP page for Chung Loong

---

docs/UserGuide.md

Update UserGuide from page 3 of UG Draft PDF

---

docs/team/minheina.md

Create PPP-MinHein for v1.1

---

docs/_data/projects.yml
docs/_sass/minima/_base.scss

Update name to FoodWhere for sitewide settings

---

docs/DeveloperGuide.md

Resolve #34. Tagging @LikHern to follow up.

Update NFRs in Developer Guide

---

docs/DeveloperGuide.md

Add more use cases to Developer Guide

---

docs/UserGuide.md

Update page 7 in User Guide for v1.1

---

docs/team/likhern.md

Create PPP-Lik Hern for v1.1

---

docs/AboutUs.md

Remove homepage URL for Chung Loong in AboutUs

---

README.md

Update README.md with correct link to CI actions

---

build.gradle

Modify build.gradle to use foodwhere

---

src/main/resources/view/ReviewListCard.fxml
src/main/resources/view/StallListCard.fxml

Remove email from User Interface

---

src/main/java/foodwhere/model/detail/Detail.java

Update Detail.java to fix JavaDocs bug

---

docs/DeveloperGuide.md

Modify DeveloperGuide.md without reference to command

---

src/main/resources/view/ReviewListCard.fxml
src/main/resources/view/StallListCard.fxml

Remove phone field from user interface

---

src/main/java/foodwhere/model/review/Date.java
src/main/java/foodwhere/model/review/Review.java
src/main/java/foodwhere/model/review/StallName.java
src/main/java/foodwhere/model/review/UniqueReviewList.java
src/main/java/foodwhere/model/review/exceptions/DuplicateReviewException.java
src/main/java/foodwhere/model/review/exceptions/ReviewNotFoundException.java

Add Review.java and related classes

---

src/main/java/foodwhere/model/review/Content.java
src/main/java/foodwhere/model/review/Review.java

Add content class as a constant field under review class

---

src/main/java/foodwhere/model/stall/Stall.java

Add Review as Stall's data class

---

docs/index.md

Modify CI and Codecov link in index.md for Github pages 

---

src/main/java/foodwhere/storage/JsonAdaptedReview.java
src/test/java/foodwhere/testutil/ReviewBuilder.java

Remove reference to Name class in ReviewBuilder and JSONAdaptedReview

---

src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/model/review/ContentTest.java
src/test/java/foodwhere/model/review/DateTest.java
src/test/java/foodwhere/model/review/ReviewTest.java
src/test/java/foodwhere/model/review/UniqueReviewListTest.java
src/test/java/foodwhere/testutil/ReviewBuilder.java
src/test/java/foodwhere/testutil/TypicalReviews.java

Add test coverage for review data classes

---

src/main/java/foodwhere/model/Model.java
src/main/java/foodwhere/model/ModelManager.java
src/test/java/foodwhere/logic/commands/SAddCommandTest.java

Modify model data classes to include review related method

---

src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/model/Model.java
src/main/java/foodwhere/model/ModelManager.java
src/main/java/foodwhere/ui/ReviewCard.java
src/main/resources/view/ReviewListCard.fxml
src/test/java/foodwhere/logic/commands/SAddCommandTest.java

Modify user interface and add Review methods

---

src/main/java/foodwhere/model/stall/Stall.java
src/main/java/foodwhere/model/util/SampleDataUtil.java
src/test/java/foodwhere/model/stall/StallTest.java
src/test/java/foodwhere/testutil/StallBuilder.java
src/test/java/foodwhere/testutil/TestUtil.java

Add review related test cases for StallTest

---

build.gradle
docs/UserGuide.md
src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/logic/commands/SAddCommand.java
src/main/java/foodwhere/model/UserPrefs.java
src/main/java/foodwhere/model/util/SampleDataUtil.java
src/main/java/foodwhere/storage/JsonSerializableAddressBook.java
src/main/java/foodwhere/ui/ReviewCard.java
src/main/java/foodwhere/ui/StallCard.java

Modify sample data and JAR details

---

docs/UserGuide.md

Modify user guide formatting and command details

---

src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/logic/parser/CliSyntax.java
src/main/java/foodwhere/logic/parser/ParserUtil.java
src/main/java/foodwhere/logic/parser/RAddCommandParser.java
src/main/java/foodwhere/model/review/Rating.java
src/main/java/foodwhere/model/review/Review.java
src/main/java/foodwhere/model/util/SampleDataUtil.java
src/main/java/foodwhere/storage/JsonAdaptedReview.java
src/main/java/foodwhere/ui/ReviewCard.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/ReviewListCard.fxml
src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/model/review/RatingTest.java
src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
src/test/java/foodwhere/testutil/ReviewBuilder.java
src/test/java/foodwhere/testutil/TypicalReviews.java

Add Rating class to Review

---

src/main/java/foodwhere/model/review/Date.java
src/test/java/foodwhere/model/review/DateTest.java
src/test/java/foodwhere/testutil/TypicalReviews.java

Add Date parsing

---

src/main/java/foodwhere/model/util/SampleDataUtil.java

Modify SampleDataUtil.java to change date format

---

src/main/java/foodwhere/logic/commands/SEditCommand.java
src/main/java/foodwhere/logic/parser/AddressBookParser.java
src/main/java/foodwhere/logic/parser/SEditCommandParser.java
src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/logic/commands/EditCommandTest.java
src/test/java/foodwhere/logic/commands/EditStallDescriptorTest.java
src/test/java/foodwhere/logic/commands/SEditCommandTest.java
src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
src/test/java/foodwhere/logic/parser/SEditCommandParserTest.java
src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
src/test/java/foodwhere/testutil/StallUtil.java

Add edit stall function

---

src/main/java/foodwhere/logic/commands/REditCommand.java
src/main/java/foodwhere/logic/parser/AddressBookParser.java
src/main/java/foodwhere/logic/parser/REditCommandParser.java

Resolve #164 
- Unit test not added yet for edit review

Add Edit Review functionality

---

src/main/java/foodwhere/logic/commands/RAddCommand.java

Fix incorrect date format in RAdd prompt

---

src/main/java/foodwhere/MainApp.java

Update MainApp version number for trial release

---

src/main/java/foodwhere/logic/parser/REditCommandParser.java
src/test/java/foodwhere/logic/commands/RAddCommandTest.java

Resolve #195 
Tag - Pass
Date - Pass
Content -Pass
Rating - Pass

Edit parser to parse correct review prefixes

---

src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/ui/ReviewListPanel.java
src/main/java/foodwhere/ui/StallListPanel.java

Fix Panel throwing NullPointerException

---

src/main/java/foodwhere/logic/commands/SEditCommand.java
src/main/java/foodwhere/model/AddressBook.java
src/main/java/foodwhere/storage/JsonAdaptedStall.java
src/main/java/foodwhere/storage/JsonSerializableAddressBook.java
src/test/java/foodwhere/logic/commands/SFindCommandTest.java
src/test/java/foodwhere/model/AddressBookTest.java
src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
src/test/java/foodwhere/storage/JsonAddressBookStorageTest.java
src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java

Make reviews in AddressBook follow Reviews stored in in Stall

---

src/main/java/foodwhere/logic/commands/RSortCommand.java
src/main/java/foodwhere/logic/commands/SSortCommand.java
src/main/java/foodwhere/logic/parser/AddressBookParser.java
src/main/java/foodwhere/logic/parser/ParserUtil.java
src/main/java/foodwhere/logic/parser/RSortCommandParser.java
src/main/java/foodwhere/logic/parser/SSortCommandParser.java
src/main/java/foodwhere/model/AddressBook.java
src/main/java/foodwhere/model/Model.java
src/main/java/foodwhere/model/ModelManager.java
src/main/java/foodwhere/model/review/UniqueReviewList.java
src/main/java/foodwhere/model/review/comparator/DateComparator.java
src/main/java/foodwhere/model/review/comparator/NameComparator.java
src/main/java/foodwhere/model/review/comparator/RatingComparator.java
src/main/java/foodwhere/model/review/comparator/ReviewsComparatorList.java
src/main/java/foodwhere/model/stall/UniqueStallList.java
src/main/java/foodwhere/model/stall/comparator/NameComparator.java
src/main/java/foodwhere/model/stall/comparator/StallsComparatorList.java
src/test/java/foodwhere/logic/commands/SAddCommandTest.java

Modify and add sort functions

---

src/main/java/foodwhere/commons/core/Messages.java
src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/logic/parser/ParserUtil.java
src/main/java/foodwhere/logic/parser/RAddCommandParser.java
src/main/java/foodwhere/logic/parser/REditCommandParser.java
src/main/java/foodwhere/logic/parser/SAddCommandParser.java
src/main/java/foodwhere/model/review/Rating.java
src/main/java/foodwhere/model/review/ReviewBuilder.java
src/main/java/foodwhere/model/util/SampleDataUtil.java
src/main/java/foodwhere/storage/JsonAdaptedReview.java
src/test/java/foodwhere/logic/parser/RAddCommandParserTest.java
src/test/java/foodwhere/logic/parser/SAddCommandParserTest.java
src/test/java/foodwhere/model/review/NameContainsStallPredicateTest.java
src/test/java/foodwhere/model/review/RatingTest.java

Add error messages for missing fields and resolve NumberFormatException

---

src/main/java/foodwhere/logic/parser/ParserUtil.java
src/main/java/foodwhere/logic/parser/RFindCommandParser.java
src/main/java/foodwhere/logic/parser/SFindCommandParser.java
src/test/java/foodwhere/logic/parser/ParserUtilTest.java
src/test/java/foodwhere/logic/parser/RFindCommandParserTest.java
src/test/java/foodwhere/logic/parser/SFindCommandParserTest.java
src/test/java/foodwhere/model/stall/StallContainsKeywordsPredicateTest.java

Fix bug where find using multiple keywords does not return expected results

Fix bug in SFind and RFind commands

---

docs/UserGuide.md

Update UserGuide with sedit and redit details

---

docs/UserGuide.md

Fix user guide for incorrect date format

---

src/main/java/foodwhere/ui/CopyMenuItem.java
src/main/java/foodwhere/ui/ReviewListPanel.java

Add copying of Address for Review

---

docs/UserGuide.md
src/main/java/foodwhere/model/review/comparator/NameComparator.java
src/main/java/foodwhere/model/review/comparator/ReviewsComparatorList.java
src/main/java/foodwhere/model/stall/comparator/NameComparator.java
src/main/java/foodwhere/model/stall/comparator/StallsComparatorList.java

Update User Guide to include ssort and rsort commands

---

src/main/java/foodwhere/MainApp.java

Update MainApp version number

---

src/main/java/foodwhere/model/review/Review.java
src/main/java/foodwhere/model/stall/Stall.java
src/main/java/foodwhere/ui/CopyMenuItem.java
src/main/java/foodwhere/ui/ReviewCard.java
src/main/java/foodwhere/ui/StallCard.java

Modify tag string returned by Copy Tag in User Interface

---

src/main/java/foodwhere/MainApp.java
src/main/java/foodwhere/logic/Logic.java
src/main/java/foodwhere/logic/commands/ClearCommand.java
src/main/java/foodwhere/logic/commands/ExitCommand.java
src/main/java/foodwhere/logic/commands/REditCommand.java
src/main/java/foodwhere/logic/commands/RFindCommand.java
src/main/java/foodwhere/logic/commands/RSortCommand.java
src/main/java/foodwhere/logic/commands/SEditCommand.java
src/main/java/foodwhere/logic/commands/SFindCommand.java
src/main/java/foodwhere/logic/commands/SSortCommand.java
src/main/java/foodwhere/model/ModelManager.java
src/main/java/foodwhere/model/commons/Address.java
src/main/java/foodwhere/model/commons/Name.java
src/main/java/foodwhere/model/commons/Tag.java
src/main/java/foodwhere/model/review/Content.java
src/main/java/foodwhere/model/review/Rating.java
src/main/java/foodwhere/storage/AddressBookStorage.java
src/main/java/foodwhere/storage/JsonAddressBookStorage.java
src/main/java/foodwhere/storage/JsonSerializableAddressBook.java
src/main/java/foodwhere/storage/StorageManager.java

Modify MainApp for AddressBook to FoodWhere

---

src/main/java/foodwhere/commons/core/GuiSettings.java
src/main/java/foodwhere/commons/core/Version.java
src/main/java/foodwhere/storage/JsonAdaptedStall.java
src/test/java/foodwhere/commons/core/ConfigTest.java
src/test/java/foodwhere/commons/core/GuiSettingsTest.java
src/test/java/foodwhere/commons/core/VersionTest.java
src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
src/test/java/foodwhere/storage/JsonUserPrefsStorageTest.java
src/test/java/foodwhere/storage/StorageManagerTest.java

Resolves #257, achieving 100% test coverage in storage.

Improve test coverage in commons and storage

---

docs/DeveloperGuide.md

Add use case for clear command in Developer Guide

---

docs/UserGuide.md

This is a long PR and will target multiple issues.
Resolves #277
Resolves #278
Resolves #279
Resolves #280
Resolves #281
Resolves #282
Resolves #285
Resolves #288
Resolves #290
Resolves #291
Resolves #294
Resolves #296
Resolves #297
Resolves #298
Resolves #299
Resolves #302
Resolves #303
Resolves #306
Resolves #307
Resolves #308
Resolves #309
Resolves #310
Resolves #311
Resolves #312
Resolves #313
Resolves #314

Fix User Guide documentation bugs

---

docs/DeveloperGuide.md

Update use cases for edit food stalls and review

---

src/main/java/foodwhere/commons/core/Messages.java
src/main/java/foodwhere/logic/commands/RAddCommand.java
src/main/java/foodwhere/logic/commands/RDeleteCommand.java
src/main/java/foodwhere/logic/commands/REditCommand.java
src/main/java/foodwhere/logic/commands/SDeleteCommand.java
src/main/java/foodwhere/logic/commands/SEditCommand.java
src/main/java/foodwhere/logic/parser/RAddCommandParser.java
src/main/java/foodwhere/logic/parser/RDeleteCommandParser.java
src/main/java/foodwhere/logic/parser/REditCommandParser.java
src/main/java/foodwhere/logic/parser/SDeleteCommandParser.java
src/main/java/foodwhere/logic/parser/SEditCommandParser.java
src/test/java/foodwhere/logic/LogicManagerTest.java
src/test/java/foodwhere/logic/commands/RAddCommandTest.java
src/test/java/foodwhere/logic/commands/RDeleteCommandTest.java
src/test/java/foodwhere/logic/commands/SDeleteCommandTest.java
src/test/java/foodwhere/logic/commands/SEditCommandTest.java
src/test/java/foodwhere/logic/parser/RDeleteCommandParserTest.java
src/test/java/foodwhere/logic/parser/SDeleteCommandParserTest.java
src/test/java/foodwhere/logic/parser/SEditCommandParserTest.java

Modify invalid index error message to be standardized

---

docs/team/minheina.md

Update minheina PPP

---

docs/DeveloperGuide.md

Update Developer Guide to fix numbering

---

docs/DeveloperGuide.md
docs/team/jamietan2002.md

Please do not merge this yet as it is an ongoing PR 
Resolves #326

Update PPP for Jamie

---

docs/UserGuide.md

Resolves #343.
Also with this update:
Updated Review uniqueness check - it also checks the set of tags
Add stored data format to explain that tags are stored as lowercase

Edit tags to use more lowercase letters

---

docs/team/likhern.md

Update PPP for Lik Hern

---

src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/logic/parser/RAddCommandParserTest.java
src/test/java/foodwhere/model/common/NameTest.java
src/test/java/foodwhere/model/commons/AddressTest.java
src/test/java/foodwhere/model/commons/NameTest.java
src/test/java/foodwhere/model/commons/TagTest.java

Add new test cases for RAddCommandParser

---

docs/team/hikoya.md

Update PPP for Chung Loong

---

src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/logic/commands/REditCommandTest.java
src/test/java/foodwhere/logic/parser/REditCommandParserTest.java
src/test/java/foodwhere/testutil/EditReviewDescriptorBuilder.java
src/test/java/foodwhere/testutil/TypicalIndexes.java

Requires @clarence-chew assistance to modify failing test case due to review edit behaviour. This PR is safe to merge and work on.

Add REdit and REditCommandParser Unit tests

---

docs/team/hikoya.md
src/main/java/foodwhere/ui/ReviewCard.java
src/main/java/foodwhere/ui/ReviewListPanel.java
src/main/java/foodwhere/ui/StallCard.java
src/main/java/foodwhere/ui/StallListPanel.java

Add @@author tags to reused code

---

docs/DeveloperGuide.md

Add Manual Test Instructions

---

src/main/java/foodwhere/logic/commands/REditCommand.java
src/test/java/foodwhere/logic/commands/CommandTestUtil.java
src/test/java/foodwhere/logic/commands/REditCommandTest.java
src/test/java/foodwhere/logic/parser/REditCommandParserTest.java

Fix REdit tests

---

src/main/java/foodwhere/logic/commands/RSortCommand.java
src/main/java/foodwhere/logic/commands/SSortCommand.java
src/test/java/foodwhere/logic/commands/RSortCommandTest.java
src/test/java/foodwhere/logic/commands/SSortCommandTest.java
src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
src/test/java/foodwhere/logic/parser/RSortCommandParserTest.java
src/test/java/foodwhere/logic/parser/SSortCommandParserTest.java

Add test cases for sort commands

---

docs/UserGuide.md

Change "capitalisation" to "capitalization"

---

docs/team/hikoya.md

Modify PPP for Chung Loong to remove extra ]

---

docs/DeveloperGuide.md

Fix DG Contents page visual bug
